package cuestionario;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristhian
 */
public class NivelPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form Panel1
     */
      DefaultTableModel dtm = new DefaultTableModel();
               String titulo[] = new String[]{"Numero", "Palabra", "Definición "};//TITULO DE LA TABLA
    public NivelPanel1() {
        initComponents();
        
        tblNivel1.setModel(dtm); 
         dtm.setColumnIdentifiers(titulo);
         //tblNivel1.getColumnModel().getColumn(0).setPreferredWidth(1);
         
          Preguntas preg = new Preguntas();
          
          for(int i =0; i<=39; i++){
              for(int j=0; j<2; j++){
        agregar(i+1,preg.matrizPalabras(i, j),preg.matrizPalabras(i, (j=+1)) );
           }
          }

        
    }
 void agregar(int id, String palabra, String definicion) {
        dtm.addRow(new Object[]{id, palabra, definicion});
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNivel1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        tblNivel1.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        tblNivel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numero", "Palabra", "Definicion"
            }
        ));
        tblNivel1.setRowHeight(40);
        jScrollPane1.setViewportView(tblNivel1);
        if (tblNivel1.getColumnModel().getColumnCount() > 0) {
            tblNivel1.getColumnModel().getColumn(0).setMinWidth(700);
            tblNivel1.getColumnModel().getColumn(0).setPreferredWidth(700);
            tblNivel1.getColumnModel().getColumn(0).setMaxWidth(700);
            tblNivel1.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblNivel1.getColumnModel().getColumn(2).setMinWidth(400);
            tblNivel1.getColumnModel().getColumn(2).setPreferredWidth(300);
        }

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Conceptos Generales");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNivel1;
    // End of variables declaration//GEN-END:variables
}
