/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

/**
 *
 * @author Cristhian
 */
public class Panel_Acerca extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Acerca
     */
    public Panel_Acerca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblconectar6 = new javax.swing.JLabel();
        lblconectar7 = new javax.swing.JLabel();
        lblconectar8 = new javax.swing.JLabel();
        lblconectar9 = new javax.swing.JLabel();
        lblconectar10 = new javax.swing.JLabel();
        lblconectar11 = new javax.swing.JLabel();
        lblconectar12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackageImages/WhatsApp Image 2020-03-18 at 9.57.55 PM.jpeg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        lblconectar6.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        lblconectar6.setForeground(new java.awt.Color(204, 204, 204));
        lblconectar6.setText("Programador");

        lblconectar7.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        lblconectar7.setForeground(new java.awt.Color(204, 204, 204));
        lblconectar7.setText("Cristhian Villota Fajardo");

        lblconectar8.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        lblconectar8.setForeground(new java.awt.Color(204, 204, 204));
        lblconectar8.setText("Correo electrónico");

        lblconectar9.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        lblconectar9.setForeground(new java.awt.Color(204, 204, 204));
        lblconectar9.setText("Telefono ");

        lblconectar10.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        lblconectar10.setForeground(new java.awt.Color(204, 204, 204));
        lblconectar10.setText("3216363932 - 3122923964");

        lblconectar11.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        lblconectar11.setForeground(new java.awt.Color(204, 204, 204));
        lblconectar11.setText("cvillota5fajardo@gmail.com");

        lblconectar12.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        lblconectar12.setForeground(new java.awt.Color(204, 204, 204));
        lblconectar12.setText("\"Proyectando el futuro\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblconectar12, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblconectar9)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblconectar6)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblconectar10, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblconectar7)
                                    .addGap(42, 42, 42))
                                .addComponent(lblconectar11, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblconectar8))
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblconectar6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(lblconectar7, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(lblconectar8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(lblconectar11, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(lblconectar9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblconectar10, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addComponent(lblconectar12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(499, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1356, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 578, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblconectar10;
    private javax.swing.JLabel lblconectar11;
    private javax.swing.JLabel lblconectar12;
    private javax.swing.JLabel lblconectar6;
    private javax.swing.JLabel lblconectar7;
    private javax.swing.JLabel lblconectar8;
    private javax.swing.JLabel lblconectar9;
    // End of variables declaration//GEN-END:variables
}
