/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;
import Main.MainPrincipal;
/**
 *
 * @author Cristhian
 */
public class Simulador extends javax.swing.JFrame implements Runnable {

    int x = 750;
    int y = 300;
    int ancho = 50;
    int alto = 200;
    int giro = 10;
    int h = 0;
    int a = 0;
    int c = 0;
    int p = 0;
    int r1 = 0;
    int r2 = 0;
    Graphics2D gra;
    Thread hilo;

    /**
     * Creates new form Frame_Contenedor
     */
    public Simulador() {
        this.setContentPane(new Graficos());

        initComponents();
        jsliHombro.setInverted(false);
        jsliHombro.setPaintTicks(true);
        jsliHombro.setMajorTickSpacing(10);//Lineas por separado 
        jsliHombro.setMinorTickSpacing(5);//lineas menores
        jsliHombro.setPaintLabels(true);

//Antebrazo
        jslAntebrazo.setInverted(false);
        jslAntebrazo.setPaintTicks(true);
        jslAntebrazo.setMajorTickSpacing(50);//Lineas por separado 
        jslAntebrazo.setMinorTickSpacing(10);//lineas menores
        jslAntebrazo.setPaintLabels(true);

        //Codo
        jslCodo.setInverted(false);
        jslCodo.setPaintTicks(true);
        jslCodo.setMajorTickSpacing(50);//Lineas por separado 
        jslCodo.setMinorTickSpacing(10);//lineas menores
        jslCodo.setPaintLabels(true);

        //Pinza
        jslPinza.setInverted(false);
        jslPinza.setPaintTicks(true);
        jslPinza.setMajorTickSpacing(50);//Lineas por separado 
        jslPinza.setMinorTickSpacing(10);//lineas menores
        jslPinza.setPaintLabels(true);

        //Rodamientos uno
        jslRodamientos1.setInverted(false);
        jslRodamientos1.setPaintTicks(true);
        jslRodamientos1.setMajorTickSpacing(100);//Lineas por separado 
        jslRodamientos1.setMinorTickSpacing(50);//lineas menores
        jslRodamientos1.setPaintLabels(true);

        //Rodamientos 2
        jslRodamientos2.setInverted(false);
        jslRodamientos2.setPaintTicks(true);
        jslRodamientos2.setMajorTickSpacing(50);//Lineas por separado 
        jslRodamientos2.setMinorTickSpacing(10);//lineas menores
        jslRodamientos2.setPaintLabels(true);

       
  
        
        hilo = new Thread((Runnable) this);
        hilo.start();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jsliHombro = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jslAntebrazo = new javax.swing.JSlider();
        jPanel20 = new javax.swing.JPanel();
        jslCodo = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jslPinza = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jslRodamientos1 = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jslRodamientos2 = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        lblHombro = new javax.swing.JLabel();
        lblAntebrazo = new javax.swing.JLabel();
        lblCodo = new javax.swing.JLabel();
        lblPinza = new javax.swing.JLabel();
        lblRodamientos1 = new javax.swing.JLabel();
        lblRodamientos2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel17.setBackground(new java.awt.Color(0, 102, 102));

        jPanel18.setBackground(new java.awt.Color(0, 51, 51));

        jsliHombro.setMaximum(110);
        jsliHombro.setMinimum(70);

        jLabel3.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Hombro");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jsliHombro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jsliHombro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(0, 51, 51));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("AnteBrazo");

        jslAntebrazo.setMaximum(165);
        jslAntebrazo.setValue(150);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jslAntebrazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jslAntebrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel20.setBackground(new java.awt.Color(0, 51, 51));

        jslCodo.setMaximum(170);
        jslCodo.setValue(150);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Codo");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jslCodo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jslCodo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(25, 25, 25))
        );

        jPanel21.setBackground(new java.awt.Color(0, 51, 51));

        jslPinza.setMaximum(80);
        jslPinza.setMinimum(-18);

        jLabel8.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Pinza");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jslPinza, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jslPinza, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));

        jslRodamientos1.setMaximum(500);
        jslRodamientos1.setMinimum(-400);

        jLabel9.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Derecha");

        jLabel12.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Izquierda");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jslRodamientos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jslRodamientos1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(31, 31, 31))
        );

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));

        jslRodamientos2.setMaximum(1000);
        jslRodamientos2.setMinimum(750);

        jLabel10.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Atras");

        jLabel11.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Adelante");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jslRodamientos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jslRodamientos2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEnviar.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        btnEnviar.setText("Anterior");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        lblHombro.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        lblHombro.setForeground(new java.awt.Color(51, 51, 51));
        lblHombro.setText("0");

        lblAntebrazo.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        lblAntebrazo.setForeground(new java.awt.Color(51, 51, 51));
        lblAntebrazo.setText("0");

        lblCodo.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        lblCodo.setForeground(new java.awt.Color(51, 51, 51));
        lblCodo.setText("0");

        lblPinza.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        lblPinza.setForeground(new java.awt.Color(51, 51, 51));
        lblPinza.setText("0");

        lblRodamientos1.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        lblRodamientos1.setForeground(new java.awt.Color(51, 51, 51));
        lblRodamientos1.setText("0");

        lblRodamientos2.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        lblRodamientos2.setForeground(new java.awt.Color(51, 51, 51));
        lblRodamientos2.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHombro, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(lblAntebrazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPinza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRodamientos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRodamientos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(814, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblHombro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblAntebrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(lblCodo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(lblPinza, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(lblRodamientos1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(lblRodamientos2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
     new Main.MainPrincipal().setVisible(true);
     setVisible(false);
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSlider jslAntebrazo;
    private javax.swing.JSlider jslCodo;
    private javax.swing.JSlider jslPinza;
    private javax.swing.JSlider jslRodamientos1;
    private javax.swing.JSlider jslRodamientos2;
    private javax.swing.JSlider jsliHombro;
    private javax.swing.JLabel lblAntebrazo;
    private javax.swing.JLabel lblCodo;
    private javax.swing.JLabel lblHombro;
    private javax.swing.JLabel lblPinza;
    private javax.swing.JLabel lblRodamientos1;
    private javax.swing.JLabel lblRodamientos2;
    // End of variables declaration//GEN-END:variables

    public class Graficos extends JPanel {

        @Override
        public void paint(Graphics g) {
            super.paint(g);

            //plano cartesiano X
            Graphics2D planoX = (Graphics2D) g;
            planoX.setColor(Color.BLACK);
            planoX.fillRect(880, 0, 5, 700);
            
            //Plano cartesiano Y
            Graphics2D planoY = (Graphics2D) g;
            planoY.translate(1422, 350);
            planoY.rotate(Math.toRadians(90));
            planoY.setColor(Color.BLACK);
            planoY.fillRect(0, 0, 5, 1000);
            
            
            //Hombro
            Graphics2D g2d = (Graphics2D) g;
            g2d.translate(x, y);
            g2d.rotate(Math.toRadians(h-10));
            g2d.setColor(Color.black);
            g2d.fillRect(r1, 0+r2, ancho, alto);
            
            g2d.setColor(Color.BLUE);
            g2d.fillRect(r1, 0+r2, ancho-30, alto);
            
            
            g2d.setColor(Color.BLUE);
            g2d.fillOval(r1, -40+r2, 50, 50);

            g2d.setColor(Color.GREEN);
            g2d.fillOval(r1+5, -35+r2, 40, 40);

            //base lateral
            g2d.setColor(Color.GRAY);
            g2d.fillRect((-55 + r1), -90+r2, 180, 50);
            
            g2d.setColor(Color.black);
            g2d.fillRect((-55 + r1), -90+r2, 180, 20);
            
            //Base horizontal
            g2d.setColor(Color.GREEN);
            g2d.fillRect(r1, -210+r2, 50, 120);

            g2d.setColor(Color.red);
            g2d.fillRect(r1, -210+r2, 30, 120);

            
            g2d.setColor(Color.blue);
            g2d.fillRect(r1-60, -240+r2, 200, 40);

            g2d.setColor(Color.black);
            g2d.fillRect(r1-60, -240+r2, 200, 20);

             //rodamientos 1
            g2d.setColor(Color.BLACK);
            g2d.fillOval(r1-120, -260+r2, 80, 80);
 
            g2d.setColor(Color.red);
            g2d.fillOval(r1-110, -250+r2, 60, 60);
 
            //rodamientos 2
            g2d.setColor(Color.BLACK);
            g2d.fillOval(r1+120, -260+r2, 80, 80);
            
            g2d.setColor(Color.red);
            g2d.fillOval(r1+130, -250+r2, 60, 60);
 
             
            //Antebrazo
            Graphics2D g2d1 = (Graphics2D) g;
            g2d1.translate(r1, y - 100+r2);
            g2d1.rotate(Math.toRadians(a));
            g2d1.setColor(Color.red);
            g2d1.fillRect(0, 0, ancho, alto-20);
          
            g2d1.setColor(Color.darkGray);
            g2d1.fillRect(0, 0, ancho-30, alto-20);
          
            
            g2d1.setColor(Color.BLUE);
            g2d1.fillOval(0, -40, 50, 50);
          
            g2d1.setColor(Color.GREEN);
            g2d1.fillOval(5, -35, 40, 40);

            //Codo
            Graphics2D g2d2 = (Graphics2D) g;
            g2d2.translate(0, y - 130);
            g2d2.rotate(Math.toRadians(c));
            g2d2.setColor(Color.YELLOW);
            g2d2.fillRect(0, 0, ancho-10, alto-20);
            
            g2d2.setColor(Color.CYAN);
            g2d2.fillRect(0, 0, ancho-30, alto-20);
            
            
            g2d2.setColor(Color.BLUE);
            g2d2.fillOval(-5, -35, 50, 50);

            g2d2.setColor(Color.GREEN);
            g2d2.fillOval(0, -30, 40, 40);

            //Pinza
            Graphics2D g2d3 = (Graphics2D) g;
            g2d3.translate(30, y - 100);
            g2d3.rotate(Math.toRadians(p - 70));
            g2d3.setColor(Color.black);
            g2d3.fillRect(0, 0, 20, 80);

            //g2d3.translate(90, y-50);
            g2d3.rotate(Math.toRadians(p));
            g2d3.setColor(Color.black);
            g2d3.fillRect(-30, 0, 20, 80);

            g2d3.setColor(Color.BLUE);
            g2d3.fillOval(-20, -20, 30, 30);
          
            g2d3.setColor(Color.GREEN);
            g2d3.fillOval(-15, -15, 20, 20);
          
            //Plano cartesiano
        }

    }

    public void run() {

        Thread ct = Thread.currentThread();

        while (ct == hilo) {
            repaint();
            h = jsliHombro.getValue();
            lblHombro.setText("Hombro: "+h+"º");
            
            a = jslAntebrazo.getValue();
            lblAntebrazo.setText("Antebrazo: "+a+"º");
            
            c = jslCodo.getValue();
            lblCodo.setText("Codo: "+c+"º");
            
            p = jslPinza.getValue();
            lblPinza.setText("Pinza: "+p+"º");
            
            r1 = jslRodamientos1.getValue();
            lblRodamientos1.setText("X: "+r1+"º");
            
            r2 = jslRodamientos2.getValue();
            lblRodamientos2.setText("Y: "+r2+"º");
            //valorJ();
            try {
                Thread.sleep(10);

            } catch (InterruptedException e) {
                System.err.println(e);

            }

        }
    }

}
